//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerManagementViettelApp.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DichVu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DichVu()
        {
            this.LichSuDangKies = new HashSet<LichSuDangKy>();
            this.TaiKhoanDichVus = new HashSet<TaiKhoanDichVu>();
        }
    
        public int MaDichVu { get; set; }
        public string TenDichVu { get; set; }
        public Nullable<double> Gia { get; set; }
        public Nullable<double> KhuyenMai { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> MaDanhMuc { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
    
        public virtual DanhMuc DanhMuc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuDangKy> LichSuDangKies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaiKhoanDichVu> TaiKhoanDichVus { get; set; }
    }
}
