//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerManagementViettelApp.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichSuDangKy
    {
        public int MaDichVu { get; set; }
        public Nullable<double> Gia { get; set; }
        public string TenTaiKhoan { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
    
        public virtual DichVu DichVu { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
